version: '3.8'

services:
  # 1. Сервис базы данных
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=MyBD
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - "5433:5432" # Прокидываем порт, чтобы ты могла зайти в базу через PGAdmin, если надо

  # 2. Сервис твоего Django-сайта
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 abiturient_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=MyBD
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1
      - DATABASE_HOST=db  # Имя сервиса базы данных выше
      - DATABASE_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: